# Generated by Django 4.1.4 on 2023-03-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Topic title')),
                ('author', models.CharField(max_length=200, verbose_name=' Content Author')),
                ('content', models.TextField(max_length=1000, verbose_name=' Content ')),
                ('image', models.ImageField(upload_to='blogimages', verbose_name='Add Topic Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
